backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mpesa.urls import mpesa_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('',include('django.contrib.auth.urls')),
    path('mpesa/', include(mpesa_urls)),
    path('',include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns= [
    path('',views.home,name='home'),
    path('home',views.index,name='index'),
    path('admin_template/', views.admin, name='admin_template'),
    path('user_stats/', views.user_stats, name='user_stats'),
    path('rating_distribution/', views.rating_distribution, name='rating_distribution'),
    path('settings', views.settings, name='settings'),

    path('users', views.users, name='users'),
    path('add_user/', views.add_user, name='add_user'),
    path('edit_user/<int:pk>/', views.edit_user, name='edit_user'),
    path('delete_user/<int:pk>/', views.delete_user, name='delete_user'),

    
    path('buses', views.buses, name='buses'),
    path('add_bus/', views.add_bus, name='add_bus'),
    path('edit_bus/<int:pk>/', views.edit_bus, name='edit_bus'),
    path('delete_bus/<int:pk>/', views.delete_bus, name='delete_bus'),

    path('schedule/', views.schedules, name='schedule'),
    path('add_schedule/', views.add_schedule, name='add_schedule'),
    path('edit_schedule/<int:schedule_id>/', views.edit_schedule, name='edit_schedule'),
    path('delete_schedule/<int:schedule_id>/', views.delete_schedule, name='delete_schedule'),

    path('routes_admin', views.routes_admin, name='routes_admin'),
    path('routes_admin/add/', views.add_route, name='add_route'),
    path('routes_admin/edit/<str:route_id>/', views.edit_route, name='edit_route'),
    path('routes_admin/delete/<str:route_id>/', views.delete_route, name='delete_route'),


    path('gender/', views.gender, name='gender'),

    path('search_results/', views.search_results, name='search_results'),
    path('search_view/', views.search_view, name='search_view'),
    
    path('booking_form/', views.booking_form, name='booking_form'),
    path('booking_form/add/', views.add_booking, name='add_booking'),
    path('edit_booking/<int:booking_id>/', views.edit_booking, name='edit_booking'),
    path('delete_booking/<int:booking_id>/', views.delete_booking, name='delete_booking'),

    path('sign_up',views.signUp,name='sign_up'),
    path("verify-email/<slug:username>", views.verifyEmail, name="verify-email"),
    path("resend-otp", views.resendOtp, name="resend-otp"),
    path('login_user', views.login_user, name="login"),

    path('routes/', views.routes_view, name='routes'),

    path('seat-selection/<int:bus_id>/', views.seat_selection_view, name='seat_selection'),
    path('booking_details/<str:selected_seats>/', views.booking_details, name='booking_details'),
    path('payment/<int:booking_id>/', views.payment, name='payment'),
    path('logout_user', views.logout_user, name='logout'),
    path('lockscreen', views.lockscreen, name='lockscreen'),

    path('booking', views.booking, name='booking'),
    path('generate_pdf/', views.generate_pdf, name='generate_pdf'),

    path('inbox/notifications/', include('notifications.urls', namespace='notifications')),
    path('notifications/mark-all-as-read/', views.mark_all_as_read, name='mark_all_as_read'),
    path('notifications/unread/', views.unread_notifications, name='notifications_unread'),


    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('submit_feedback/', views.submit_feedback, name='submit_feedback'),
    path('feedback/', views.feedback_list, name='feedback_list'),

    path('booking_number/', views.booking_number, name='booking_number'),
    path('booking1/<int:phone_number>', views.booking1, name='booking'),

    path('mpesa/', views.mpesa_callback, name='mpesa')
]

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model 
from .models import Profile, Bus, Schedule, Booking , Bus, Feedback


class RegisterForm(UserCreationForm):
    email=forms.CharField(widget=forms.EmailInput(attrs={"placeholder": "Enter email-address", "class": "form-control"}))
    
    
    class Meta:
        model = get_user_model()
        fields = ["username","email", "password1", "password2"]

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        # Customize form fields if needed
        self.fields['username'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Username'})
        self.fields['password'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Password'})

class BookingDetailsForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    primary_email = forms.EmailField(max_length=255, required=True)
    phone_number = forms.CharField(max_length=20, required=True)
    address = forms.CharField(max_length=255, required=False)
    payment_method = forms.ChoiceField(choices=Profile.PAYMENT_METHOD_CHOICES, required=True)


    class Meta:
        model = Profile
        fields = ['primary_email', 'phone_number', 'address', 'payment_method']

class BusForm(forms.ModelForm):
    class Meta:
        model = Bus
        fields = ['busNumber', 'capacity', 'type', 'status']


        


class BookingForm(forms.ModelForm):
    
    user =  forms.CharField(max_length=30, required=True)
    scheduleID =  forms.CharField(max_length=20, required=True)
    seatNumber = forms.CharField(max_length=255, required=False)
    totalPrice = forms.NumberInput(attrs={'class': 'form-control'})
        
    class Meta:
        model = Booking
        fields = ['user', 'scheduleID' , 'seatNumber', 'totalPrice']


class BusForm(forms.ModelForm):
    class Meta:
        model = Bus
        fields = ['busNumber', 'capacity', 'type', 'status']


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['rating', 'comments', 'suggestions']  # Include suggestions field
        widgets = {
            'comments': forms.Textarea(attrs={'placeholder': 'Your comments...'}),
            'suggestions': forms.Textarea(attrs={'placeholder': 'Any suggestions...'}),
        }

templates/add_booking.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Booking</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <style>
        .form-container {
            max-width: 600px;
            margin: auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
        }
        .form-group label {
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="container my-4">
        <h4>Add Booking</h4>
        <form method="post" class="form-container">
            {% csrf_token %}
            <div class="form-group">
                <label for="user">User</label>
                <select class="form-control" id="user" name="user" required>
                    {% for profile in profiles %}
                        <option value="{{ profile.id }}">{{ profile.username }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="scheduleID">Schedule</label>
                <select class="form-control" id="scheduleID" name="scheduleID" required>
                    {% for schedule in schedules %}
                        <option value="{{ schedule.id }}">{{ schedule }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="seatNumber">Seat Number</label>
                <input type="text" class="form-control" id="seatNumber" name="seatNumber" required>
            </div>
            <div class="form-group">
                <label for="totalPrice">Total Price</label>
                <input type="number" class="form-control" id="totalPrice" name="totalPrice" step="0.01" required>
            </div>
            <button type="submit" class="btn btn-primary">Add Booking</button>
            <a href="{% url 'bookings' %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>
</body>
</html>

templates/add_route.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>Add Route</title>
</head>

<body>
    <div class="container my-4">
        <h4>Add Route</h4>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="routeID">Route ID</label>
                <input type="text" class="form-control" id="routeID" name="routeID" required>
            </div>
            <div class="form-group">
                <label for="origin">Origin</label>
                <input type="text" class="form-control" id="origin" name="origin" required>
            </div>
            <div class="form-group">
                <label for="destination">Destination</label>
                <input type="text" class="form-control" id="destination" name="destination" required>
            </div>
            <div class="form-group">
                <label for="distance">Distance</label>
                <input type="number" step="0.01" class="form-control" id="distance" name="distance" required>
            </div>
            <div class="form-group">
                <label for="fare">Fare</label>
                <input type="number" step="0.01" class="form-control" id="fare" name="fare" required>
            </div>
            <button type="submit" class="btn btn-primary">Add Route</button>
            <a href="{% url 'routes_admin' %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
</body>

</html>

templates/admin_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="{% static 'css/dataTables.bootstrap5.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Dashboard</title>
</head>
<body>
    <!-- Top navigation bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#sidebar"
                aria-controls="offcanvasExample">
                <span class="navbar-toggler-icon" data-bs-target="#sidebar"></span>
            </button>
            <a class="navbar-brand me-auto ms-lg-0 ms-3 text-uppercase fw-bold" href="{% url 'admin_template' %}">BasiBasi</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#topNavBar"
                aria-controls="topNavBar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="topNavBar">
                <form class="d-flex ms-auto my-3 my-lg-0" action="{% url 'search_results' %}" method="get">
                    <div class="input-group">
                        <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="q" />
                        <button class="btn btn-primary" type="submit">
                            <i class="bi bi-search"></i>
                        </button>
                    </div>
                </form>
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle ms-2" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            <img src="{{ user.profile.profile_img.url }}" class="rounded-circle" alt=""
                                style="width: 40px; height: 36px; margin-right: 10px;">
                            {{ user.username }}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end">
                            <li><a class="dropdown-item" href="{% url 'settings' %}">Account Settings</a></li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- End top navigation bar -->

    <!-- Offcanvas sidebar -->
    <div class="offcanvas offcanvas-start sidebar-nav bg-dark" tabindex="-1" id="sidebar">
        <div class="offcanvas-body p-0">
            <!-- Sidebar navigation -->
            <nav class="navbar-dark">
                <ul class="navbar-nav">
                    <li>
                        <div class="text-muted small fw-bold text-uppercase px-3">
                            DASHBOARD
                        </div>
                    </li>
                    <li class="my-4">
                        <hr class="dropdown-divider bg-light" />
                    </li>
                    <li>
                        <div class="text-muted small fw-bold text-uppercase px-3 mb-3">
                            Models
                        </div>
                    </li>
                    <li>
                        <a href="#" class="nav-link px-3 sidebar-link" data-url="{% url 'users' %}">
                            <span class="me-2">
                                <span>Users</span>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link px-3 sidebar-link" data-url="{% url 'routes_admin' %}">
                            <span class="me-2">
                                <span>Routes</span>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link px-3 sidebar-link" data-url="{% url 'buses' %}">
                            <span class="me-2">
                                <span>Bus</span>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link px-3 sidebar-link" data-url="{% url 'schedule' %}">
                            <span class="me-2">
                                <span>Schedule</span>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link px-3 sidebar-link" data-url="{% url 'booking_form' %}">
                            <span class="me-2">
                                <span>Bookings</span>
                            </span>
                        </a>
                    </li>
                    <li class="my-4">
                        <hr class="dropdown-divider bg-light" />
                    </li>
                    <li>
                        <div class="text-muted small fw-bold text-uppercase px-3 mb-3">
                            Extras
                        </div>
                    </li>
                    <li>
                        <a href="#" class="nav-link px-3 sidebar-link" data-url="{% url 'gender' %}">
                            <span class="me-2">
                                <span>Gender</span>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link px-3 sidebar-link" data-url="{% url 'user_stats' %}">
                            <span class="me-2">
                                <span>User Stats</span>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link px-3 sidebar-link" data-url="{% url 'rating_distribution' %}">
                            <span class="me-2">
                                <span>Feedback Analysis</span>
                            </span>
                        </a>
                    </li>

                </ul>
            </nav>
        </div>
    </div>
    <!-- End Offcanvas sidebar -->

    <!-- Main content area -->
    <main class="mt-5 pt-3">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12" id="dashboard-content">
                    <!-- Summary, cards, and charts -->
                    <div class="row">
                        <div class="col-md-12">
                            <h4>Summary</h4>
                        </div>
                    </div>
                    <div class="row mt-4">
                        <!-- Total Users Card -->
                        <div class="col-md-3 mb-3">
                            <div class="card text-white h-100" style="background-color: #3498db;">
                                <div class="card-body py-4">
                                    <h5 class="card-title">Total Users</h5>
                                    <p class="card-text display-4">{{ total_users }}</p>
                                </div>
                            </div>
                        </div>
                        <!-- Total Buses Card -->
                        <div class="col-md-3 mb-3">
                            <div class="card text-dark h-100" style="background-color: #f1c40f;">
                                <div class="card-body py-4">
                                    <h5 class="card-title">Total Buses</h5>
                                    <p class="card-text display-4">{{ total_buses }}</p>
                                </div>
                            </div>
                        </div>
                        <!-- Total Routes Card -->
                        <div class="col-md-3 mb-3">
                            <div class="card text-white h-100" style="background-color: #2ecc71;">
                                <div class="card-body py-4">
                                    <h5 class="card-title">Total Routes</h5>
                                    <p class="card-text display-4">{{ total_routes }}</p>
                                </div>
                            </div>
                        </div>
                        <!-- Total Schedules Card -->
                        <div class="col-md-3 mb-3">
                            <div class="card text-white h-100" style="background-color: #e74c3c;">
                                <div class="card-body py-4">
                                    <h5 class="card-title">Total Schedules</h5>
                                    <p class="card-text display-4">{{ total_schedules }}</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row mt-4">
                        <!-- Average Feedback Rating Card -->
                        <div class="col-md-3 mb-3">
                            <div class="card text-white h-100" style="background-color: #f9ed07;">
                                <div class="card-body py-4">
                                    <h5 class="card-title">Average Feedback Rating</h5>
                                    <p class="card-text display-4">{{ avg_rating }}</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Charts Section -->
                    <div class="row mt-4 justify-content-center">
                        <!-- Bus Capacities Pie Chart -->
                        <div class="col-md-6">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="card-title text-center">Bus Capacities</h4>
                                    <div class="chart-container" style="position: relative; height:300px;">
                                        <canvas id="busCapacityChart"></canvas>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- End charts section -->
                </div>

                <!-- Content to be replaced dynamically -->
                <div class="col-md-12" id="content"></div>
            </div>
        </div>
    </main>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.5.1.js' %}"></script>
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap5.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <script>
        // Script for sidebar link handling
        document.querySelectorAll('.sidebar-link').forEach(link => {
            link.addEventListener('click', function(event) {
                event.preventDefault();
                const url = this.getAttribute('data-url');
                fetch(url)
                    .then(response => response.text())
                    .then(data => {
                        // Hide the dashboard content
                        document.getElementById('dashboard-content').style.display = 'none';
                        // Replace the content area with the new content
                        document.getElementById('content').innerHTML = data; 
                    });
            });
        });


// Assuming you have a Django context variable bus_data that contains capacity information
var busData = JSON.parse('{{ bus_data|escapejs }}');
var ctxBus = document.getElementById('busCapacityChart').getContext('2d');

var busCapacityChart = new Chart(ctxBus, {
    type: 'pie',
    data: {
        labels: busData.labels,
        datasets: [{
            data: busData.data,
            backgroundColor: [
                'rgba(255, 99, 132, 0.9)',  // Bright Pink
                'rgba(54, 162, 235, 0.9)',   // Bright Blue
                'rgba(255, 206, 86, 0.9)',   // Bright Yellow
                'rgba(153, 102, 255, 0.9)',  // Purple
                'rgba(75, 192, 192, 0.9)',   // Teal
                'rgba(255, 159, 64, 0.9)',   // Orange
                'rgba(255, 0, 0, 0.9)',      // Red
                'rgba(0, 128, 0, 0.9)',      // Green
                'rgba(0, 0, 255, 0.9)',      // Blue
                'rgba(255, 165, 0, 0.9)',    // Orange (vivid)
                'rgba(128, 0, 128, 0.9)',    // Purple (vivid)
                'rgba(255, 20, 147, 0.9)'    // Deep Pink
            ]

        }]
    },
    options: {
        responsive: true,
        plugins: {
            legend: {
                position: 'top',
            },
            tooltip: {
                callbacks: {
                    label: function(tooltipItem) {
                        return tooltipItem.label + ': ' + tooltipItem.raw;  // Show count/tally
                    }
                }
            }
        }
    }
});

    </script>
</body>
</html>

templates/booking_details.html
{% extends 'main/base.html' %}

{% block title %}Booking Details{% endblock %}
{% block content %}
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            line-height: 1.6;
            background-color: #f0f0f0;
            margin: 0;
            padding: 20px;
        }
        .container {
            max-width: 900px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
        }
        h1 {
            font-size: 28px;
            margin-bottom: 20px;
            color: #333;
            text-align: center;
            text-decoration: underline;
        }
        .section-container {
            display: flex;
            justify-content: space-between;
        }
        .section {
            flex: 1;
            margin: 10px;
            padding: 20px;
            background-color: #f9f9f9;
            border-radius: 8px;
        }
        .section h2 {
            font-size: 22px;
            margin-bottom: 15px;
            color: #333;
            border-bottom: 2px solid #4CAF50;
            padding-bottom: 10px;
        }
        .info {
            margin-bottom: 15px;
        }
        .info label {
            font-weight: bold;
            display: inline-block;
            width: 150px;
            color: #0f1118;
        }
        .info p {
            margin: 0;
            display: inline-block;
            color: #555;
        }
        .payment-method {
            display: flex;
            align-items: center;
            margin-bottom: 15px;
        }
        .payment-method label {
            font-weight: bold;
            margin-right: 10px;
            color: #0f1118;
        }
        .payment-method select {
            flex: 1;
            padding: 10px;
            font-size: 16px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        .button-container {
            text-align: center;
            margin-top: 20px;
        }
        .button {
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
            text-decoration: none;
            transition: background-color 0.3s, color 0.3s;
            margin: 5px;
        }
        .confirm-button {
            background-color: #007bff;
            border: none;
            color: #fff;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
            text-decoration: none;
            display: inline-block;
        }
        .confirm-button:hover {
            background-color: #0056b3;
            color: white;
        }
        .back-button {
            background-color: #f44336;
            color: white;
        }
        .back-button:hover {
            background-color: #980704;
            color: white;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Booking Details</h1>
        <form method="post">
            {% csrf_token %}
            
            <div class="section-container">
                <div class="section">
                    <h2>Trip Information</h2>
                    <div class="info">
                        <label for="origin">Origin:</label>
                        <p>{{ origin }}</p>
                    </div>
                    <div class="info">
                        <label for="destination">Destination:</label>
                        <p>{{ destination }}</p>
                    </div>
                    <div class="info">
                        <label for="departure_time">Departure Time:</label>
                        <p>{{ departure_time }}</p>
                    </div>
                    <div class="info">
                        <label for="arrival_time">Arrival Time:</label>
                        <p>{{ arrival_time }}</p>
                    </div>
                    <div class="info">
                        <label for="seat_numbers">Seat Numbers:</label>
                        <p>
                            {% for seat in selected_seats %}
                                {{ seat.seat_number }}{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </p>
                    </div>
                    <div class="info">
                        <label for="total_amount">Total Price:</label>
                        <p>Ksh {{ total_amount }}</p>
                    </div>
                </div>
                
                <div class="section">
                    <h2>Payment Information</h2>
                    <div class="payment-method">
                        <label for="id_payment_method">Select Payment Method:</label>
                        {{ form.payment_method }}
                    </div>
                </div>
            </div>
            
            <div class="button-container">
                <a href="{% url 'booking'%}" class="button confirm-button">Confirm booking</a>
                <a href="{% url 'seat_selection' bus_id=selected_seats.first.bus.id %}" class="button back-button">Back</a>
            </div>
        </form>
    </div>
</body>
</html>

{% endblock content %}

templates/delete_schedule.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>Delete Schedule</title>
</head>

<body>
    <div class="container my-4">
        <h4>Delete Schedule</h4>
        <p>Are you sure you want to delete the schedule for bus <strong>{{ schedule.bus.busNumber }}</strong> from
            <strong>{{ schedule.route.origin }}</strong> to <strong>{{ schedule.route.destination }}</strong>?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
            <a href="{% url 'schedule' %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
</body>

</html>